### ISSUE TITLE
Mood Board page setting visual display text in the header of the file.

### ISSUE THREAD

**Issue by djchateau** [michellebranch/portfolio_site#1]
# Issue

Mood Board page currently has emphasized text in the header tags instead of in a paragraph tag.

# Expected Result

Visual elements that use tags `<em>`, should only be present inside `<body>` tag. If the intent is to title the page properly for its meta data, use `<title></title>` tags for the title of the page which can be inside `<head>` tags.

Use heading tags (`<h1></h1>`-`<h6></h6>`) if you want to have a title-like display at the top of your page, but heading tags need to be in the `<body>` tags.

**Comment by djchateau** [comment]
Use [this](https://validator.w3.org/#validate_by_upload) to help validate your HTML.

**Comment by michellebranch** [comment]
mood board page fixed

**Comment by michellebranch** [comment]
fixed mood board title and formatting and both index and mood board pages html validated as correct.
